/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FeeRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'studentId' : IDL.Text,
  'dueDate' : IDL.Text,
  'collegeId' : IDL.Text,
  'paidAmount' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const StudentRecord = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Text,
  'studentId' : IDL.Text,
  'admissionYear' : IDL.Text,
  'year' : IDL.Text,
  'parentPhone' : IDL.Text,
  'section' : IDL.Text,
  'motherName' : IDL.Text,
  'totalFee' : IDL.Nat,
  'collegeId' : IDL.Text,
  'fatherName' : IDL.Text,
  'rollNumber' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'department' : IDL.Text,
  'course' : IDL.Text,
  'busFee' : IDL.Nat,
  'hostelFee' : IDL.Nat,
});
export const TeacherRecord = IDL.Record({
  'id' : IDL.Text,
  'designation' : IDL.Text,
  'joiningDate' : IDL.Text,
  'collegeId' : IDL.Text,
  'teacherId' : IDL.Text,
  'department' : IDL.Text,
  'qualification' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const College = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'address' : IDL.Text,
});
export const Notice = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'collegeId' : IDL.Text,
  'targetRole' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'principal' : IDL.Null,
  'admin' : IDL.Null,
  'feeManager' : IDL.Null,
  'teacher' : IDL.Null,
  'superAdmin' : IDL.Null,
  'student' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'collegeId' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'collegeId' : IDL.Text,
});
export const Session = IDL.Record({
  'token' : IDL.Text,
  'expiresAt' : IDL.Int,
  'userId' : IDL.Text,
  'role' : UserRole,
  'collegeId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFeeRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [FeeRecord],
      [],
    ),
  'addStudentRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [StudentRecord],
      [],
    ),
  'addTeacherRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [TeacherRecord],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createCollege' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [College],
      [],
    ),
  'createNotice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Notice],
      [],
    ),
  'createUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        UserRole,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [User],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCollege' : IDL.Func([IDL.Text, IDL.Text], [College], ['query']),
  'getSession' : IDL.Func([IDL.Text], [IDL.Opt(Session)], ['query']),
  'getStudentRecord' : IDL.Func(
      [IDL.Text, IDL.Text],
      [StudentRecord],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Text, IDL.Text], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listColleges' : IDL.Func([IDL.Text], [IDL.Vec(College)], ['query']),
  'listFeeRecords' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(FeeRecord)],
      ['query'],
    ),
  'listNotices' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Notice)], ['query']),
  'listStudentRecords' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(StudentRecord)],
      ['query'],
    ),
  'listTeacherRecords' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(TeacherRecord)],
      ['query'],
    ),
  'listUsers' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(User)],
      ['query'],
    ),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'token' : IDL.Text,
          'userId' : IDL.Text,
          'name' : IDL.Text,
          'role' : UserRole,
          'collegeId' : IDL.Text,
        }),
      ],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [], []),
  'resetPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCollege' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [College],
      [],
    ),
  'updateFeeRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [FeeRecord],
      [],
    ),
  'updateUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [User],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FeeRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'studentId' : IDL.Text,
    'dueDate' : IDL.Text,
    'collegeId' : IDL.Text,
    'paidAmount' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const StudentRecord = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Text,
    'studentId' : IDL.Text,
    'admissionYear' : IDL.Text,
    'year' : IDL.Text,
    'parentPhone' : IDL.Text,
    'section' : IDL.Text,
    'motherName' : IDL.Text,
    'totalFee' : IDL.Nat,
    'collegeId' : IDL.Text,
    'fatherName' : IDL.Text,
    'rollNumber' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'department' : IDL.Text,
    'course' : IDL.Text,
    'busFee' : IDL.Nat,
    'hostelFee' : IDL.Nat,
  });
  const TeacherRecord = IDL.Record({
    'id' : IDL.Text,
    'designation' : IDL.Text,
    'joiningDate' : IDL.Text,
    'collegeId' : IDL.Text,
    'teacherId' : IDL.Text,
    'department' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const College = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'address' : IDL.Text,
  });
  const Notice = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'collegeId' : IDL.Text,
    'targetRole' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'principal' : IDL.Null,
    'admin' : IDL.Null,
    'feeManager' : IDL.Null,
    'teacher' : IDL.Null,
    'superAdmin' : IDL.Null,
    'student' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'collegeId' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'collegeId' : IDL.Text,
  });
  const Session = IDL.Record({
    'token' : IDL.Text,
    'expiresAt' : IDL.Int,
    'userId' : IDL.Text,
    'role' : UserRole,
    'collegeId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFeeRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [FeeRecord],
        [],
      ),
    'addStudentRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [StudentRecord],
        [],
      ),
    'addTeacherRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [TeacherRecord],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createCollege' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [College],
        [],
      ),
    'createNotice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Notice],
        [],
      ),
    'createUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          UserRole,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [User],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCollege' : IDL.Func([IDL.Text, IDL.Text], [College], ['query']),
    'getSession' : IDL.Func([IDL.Text], [IDL.Opt(Session)], ['query']),
    'getStudentRecord' : IDL.Func(
        [IDL.Text, IDL.Text],
        [StudentRecord],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Text, IDL.Text], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listColleges' : IDL.Func([IDL.Text], [IDL.Vec(College)], ['query']),
    'listFeeRecords' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(FeeRecord)],
        ['query'],
      ),
    'listNotices' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Notice)],
        ['query'],
      ),
    'listStudentRecords' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(StudentRecord)],
        ['query'],
      ),
    'listTeacherRecords' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(TeacherRecord)],
        ['query'],
      ),
    'listUsers' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(User)],
        ['query'],
      ),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'token' : IDL.Text,
            'userId' : IDL.Text,
            'name' : IDL.Text,
            'role' : UserRole,
            'collegeId' : IDL.Text,
          }),
        ],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [], []),
    'resetPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCollege' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [College],
        [],
      ),
    'updateFeeRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [FeeRecord],
        [],
      ),
    'updateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [User],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };