/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface College {
  'id' : string,
  'status' : string,
  'code' : string,
  'name' : string,
  'createdAt' : bigint,
  'address' : string,
}
export interface FeeRecord {
  'id' : string,
  'status' : string,
  'studentId' : string,
  'dueDate' : string,
  'collegeId' : string,
  'paidAmount' : bigint,
  'amount' : bigint,
}
export interface Notice {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'collegeId' : string,
  'targetRole' : string,
}
export interface Session {
  'token' : string,
  'expiresAt' : bigint,
  'userId' : string,
  'role' : UserRole,
  'collegeId' : string,
}
export interface StudentRecord {
  'id' : string,
  'dob' : string,
  'studentId' : string,
  'admissionYear' : string,
  'year' : string,
  'parentPhone' : string,
  'section' : string,
  'motherName' : string,
  'totalFee' : bigint,
  'collegeId' : string,
  'fatherName' : string,
  'rollNumber' : string,
  'address' : string,
  'gender' : string,
  'department' : string,
  'course' : string,
  'busFee' : bigint,
  'hostelFee' : bigint,
}
export interface TeacherRecord {
  'id' : string,
  'designation' : string,
  'joiningDate' : string,
  'collegeId' : string,
  'teacherId' : string,
  'department' : string,
  'qualification' : string,
}
export interface User {
  'id' : string,
  'username' : string,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
  'collegeId' : string,
  'passwordHash' : string,
  'phone' : string,
}
export interface UserProfile {
  'userId' : string,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'collegeId' : string,
}
export type UserRole = { 'principal' : null } |
  { 'admin' : null } |
  { 'feeManager' : null } |
  { 'teacher' : null } |
  { 'superAdmin' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFeeRecord' : ActorMethod<
    [string, string, string, bigint, bigint, string, string],
    FeeRecord
  >,
  'addStudentRecord' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
    ],
    StudentRecord
  >,
  'addTeacherRecord' : ActorMethod<
    [string, string, string, string, string, string, string],
    TeacherRecord
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createCollege' : ActorMethod<[string, string, string, string], College>,
  'createNotice' : ActorMethod<
    [string, string, string, string, string],
    Notice
  >,
  'createUser' : ActorMethod<
    [string, string, string, string, UserRole, string, string, string],
    User
  >,
  'deleteUser' : ActorMethod<[string, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCollege' : ActorMethod<[string, string], College>,
  'getSession' : ActorMethod<[string], [] | [Session]>,
  'getStudentRecord' : ActorMethod<[string, string], StudentRecord>,
  'getUser' : ActorMethod<[string, string], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listColleges' : ActorMethod<[string], Array<College>>,
  'listFeeRecords' : ActorMethod<[string, string], Array<FeeRecord>>,
  'listNotices' : ActorMethod<[string, string], Array<Notice>>,
  'listStudentRecords' : ActorMethod<[string, string], Array<StudentRecord>>,
  'listTeacherRecords' : ActorMethod<[string, string], Array<TeacherRecord>>,
  'listUsers' : ActorMethod<[string, string, string], Array<User>>,
  'login' : ActorMethod<
    [string, string],
    {
      'token' : string,
      'userId' : string,
      'name' : string,
      'role' : UserRole,
      'collegeId' : string,
    }
  >,
  'logout' : ActorMethod<[string], undefined>,
  'resetPassword' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCollege' : ActorMethod<
    [string, string, string, string, string],
    College
  >,
  'updateFeeRecord' : ActorMethod<[string, string, bigint, string], FeeRecord>,
  'updateUser' : ActorMethod<
    [string, string, string, string, string, boolean],
    User
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];