/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Session {
    token: string;
    expiresAt: bigint;
    userId: string;
    role: UserRole;
    collegeId: string;
}
export interface FeeRecord {
    id: string;
    status: string;
    studentId: string;
    dueDate: string;
    collegeId: string;
    paidAmount: bigint;
    amount: bigint;
}
export interface User {
    id: string;
    username: string;
    name: string;
    createdAt: bigint;
    createdBy: string;
    role: UserRole;
    isActive: boolean;
    email: string;
    collegeId: string;
    passwordHash: string;
    phone: string;
}
export interface College {
    id: string;
    status: string;
    code: string;
    name: string;
    createdAt: bigint;
    address: string;
}
export interface Notice {
    id: string;
    title: string;
    content: string;
    createdAt: bigint;
    createdBy: string;
    collegeId: string;
    targetRole: string;
}
export interface StudentRecord {
    id: string;
    dob: string;
    studentId: string;
    admissionYear: string;
    year: string;
    parentPhone: string;
    section: string;
    motherName: string;
    totalFee: bigint;
    collegeId: string;
    fatherName: string;
    rollNumber: string;
    address: string;
    gender: string;
    department: string;
    course: string;
    busFee: bigint;
    hostelFee: bigint;
}
export interface TeacherRecord {
    id: string;
    designation: string;
    joiningDate: string;
    collegeId: string;
    teacherId: string;
    department: string;
    qualification: string;
}
export interface UserProfile {
    userId: string;
    name: string;
    role: UserRole;
    email: string;
    collegeId: string;
}
export enum UserRole {
    principal = "principal",
    admin = "admin",
    feeManager = "feeManager",
    teacher = "teacher",
    superAdmin = "superAdmin",
    student = "student"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFeeRecord(token: string, collegeId: string, studentId: string, amount: bigint, paidAmount: bigint, dueDate: string, status: string): Promise<FeeRecord>;
    addStudentRecord(token: string, collegeId: string, studentId: string, department: string, year: string, course: string, section: string, rollNumber: string, admissionYear: string, fatherName: string, motherName: string, parentPhone: string, address: string, dob: string, gender: string, totalFee: bigint, hostelFee: bigint, busFee: bigint): Promise<StudentRecord>;
    addTeacherRecord(token: string, collegeId: string, teacherId: string, department: string, designation: string, qualification: string, joiningDate: string): Promise<TeacherRecord>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createCollege(token: string, name: string, code: string, address: string): Promise<College>;
    createNotice(token: string, collegeId: string, title: string, content: string, targetRole: string): Promise<Notice>;
    createUser(token: string, username: string, email: string, password: string, role: UserRole, collegeId: string, name: string, phone: string): Promise<User>;
    deleteUser(token: string, userId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCollege(token: string, collegeId: string): Promise<College>;
    getSession(token: string): Promise<Session | null>;
    getStudentRecord(token: string, studentId: string): Promise<StudentRecord>;
    getUser(token: string, userId: string): Promise<User>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listColleges(token: string): Promise<Array<College>>;
    listFeeRecords(token: string, collegeId: string): Promise<Array<FeeRecord>>;
    listNotices(token: string, collegeId: string): Promise<Array<Notice>>;
    listStudentRecords(token: string, collegeId: string): Promise<Array<StudentRecord>>;
    listTeacherRecords(token: string, collegeId: string): Promise<Array<TeacherRecord>>;
    listUsers(token: string, collegeId: string, roleFilter: string): Promise<Array<User>>;
    login(username: string, password: string): Promise<{
        token: string;
        userId: string;
        name: string;
        role: UserRole;
        collegeId: string;
    }>;
    logout(token: string): Promise<void>;
    resetPassword(token: string, userId: string, newPassword: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCollege(token: string, collegeId: string, name: string, address: string, status: string): Promise<College>;
    updateFeeRecord(token: string, feeRecordId: string, paidAmount: bigint, status: string): Promise<FeeRecord>;
    updateUser(token: string, userId: string, name: string, email: string, phone: string, isActive: boolean): Promise<User>;
}
import type { Session as _Session, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFeeRecord(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: string): Promise<FeeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeeRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeeRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addStudentRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string, arg12: string, arg13: string, arg14: string, arg15: bigint, arg16: bigint, arg17: bigint): Promise<StudentRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudentRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudentRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
            return result;
        }
    }
    async addTeacherRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<TeacherRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeacherRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeacherRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCollege(arg0: string, arg1: string, arg2: string, arg3: string): Promise<College> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollege(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollege(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createNotice(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Notice> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotice(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotice(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: UserRole, arg5: string, arg6: string, arg7: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2, arg3, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
                return from_candid_User_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2, arg3, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7);
            return from_candid_User_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollege(arg0: string, arg1: string): Promise<College> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollege(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollege(arg0, arg1);
            return result;
        }
    }
    async getSession(arg0: string): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentRecord(arg0: string, arg1: string): Promise<StudentRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentRecord(arg0, arg1);
            return result;
        }
    }
    async getUser(arg0: string, arg1: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0, arg1);
                return from_candid_User_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0, arg1);
            return from_candid_User_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listColleges(arg0: string): Promise<Array<College>> {
        if (this.processError) {
            try {
                const result = await this.actor.listColleges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listColleges(arg0);
            return result;
        }
    }
    async listFeeRecords(arg0: string, arg1: string): Promise<Array<FeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeeRecords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeeRecords(arg0, arg1);
            return result;
        }
    }
    async listNotices(arg0: string, arg1: string): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotices(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotices(arg0, arg1);
            return result;
        }
    }
    async listStudentRecords(arg0: string, arg1: string): Promise<Array<StudentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudentRecords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudentRecords(arg0, arg1);
            return result;
        }
    }
    async listTeacherRecords(arg0: string, arg1: string): Promise<Array<TeacherRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeacherRecords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeacherRecords(arg0, arg1);
            return result;
        }
    }
    async listUsers(arg0: string, arg1: string, arg2: string): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers(arg0, arg1, arg2);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers(arg0, arg1, arg2);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        token: string;
        userId: string;
        name: string;
        role: UserRole;
        collegeId: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async resetPassword(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCollege(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<College> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollege(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollege(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateFeeRecord(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<FeeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeeRecord(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeeRecord(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_User_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_User_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Session_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_User_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : from_candid_Session_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: string;
    name: string;
    role: _UserRole;
    email: string;
    collegeId: string;
}): {
    userId: string;
    name: string;
    role: UserRole;
    email: string;
    collegeId: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        role: from_candid_UserRole_n7(_uploadFile, _downloadFile, value.role),
        email: value.email,
        collegeId: value.collegeId
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    expiresAt: bigint;
    userId: string;
    role: _UserRole;
    collegeId: string;
}): {
    token: string;
    expiresAt: bigint;
    userId: string;
    role: UserRole;
    collegeId: string;
} {
    return {
        token: value.token,
        expiresAt: value.expiresAt,
        userId: value.userId,
        role: from_candid_UserRole_n7(_uploadFile, _downloadFile, value.role),
        collegeId: value.collegeId
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    userId: string;
    name: string;
    role: _UserRole;
    collegeId: string;
}): {
    token: string;
    userId: string;
    name: string;
    role: UserRole;
    collegeId: string;
} {
    return {
        token: value.token,
        userId: value.userId,
        name: value.name,
        role: from_candid_UserRole_n7(_uploadFile, _downloadFile, value.role),
        collegeId: value.collegeId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    username: string;
    name: string;
    createdAt: bigint;
    createdBy: string;
    role: _UserRole;
    isActive: boolean;
    email: string;
    collegeId: string;
    passwordHash: string;
    phone: string;
}): {
    id: string;
    username: string;
    name: string;
    createdAt: bigint;
    createdBy: string;
    role: UserRole;
    isActive: boolean;
    email: string;
    collegeId: string;
    passwordHash: string;
    phone: string;
} {
    return {
        id: value.id,
        username: value.username,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        role: from_candid_UserRole_n7(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        collegeId: value.collegeId,
        passwordHash: value.passwordHash,
        phone: value.phone
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: null;
} | {
    admin: null;
} | {
    feeManager: null;
} | {
    teacher: null;
} | {
    superAdmin: null;
} | {
    student: null;
}): UserRole {
    return "principal" in value ? UserRole.principal : "admin" in value ? UserRole.admin : "feeManager" in value ? UserRole.feeManager : "teacher" in value ? UserRole.teacher : "superAdmin" in value ? UserRole.superAdmin : "student" in value ? UserRole.student : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n5(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: string;
    name: string;
    role: UserRole;
    email: string;
    collegeId: string;
}): {
    userId: string;
    name: string;
    role: _UserRole;
    email: string;
    collegeId: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        role: to_candid_UserRole_n3(_uploadFile, _downloadFile, value.role),
        email: value.email,
        collegeId: value.collegeId
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    principal: null;
} | {
    admin: null;
} | {
    feeManager: null;
} | {
    teacher: null;
} | {
    superAdmin: null;
} | {
    student: null;
} {
    return value == UserRole.principal ? {
        principal: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.feeManager ? {
        feeManager: null
    } : value == UserRole.teacher ? {
        teacher: null
    } : value == UserRole.superAdmin ? {
        superAdmin: null
    } : value == UserRole.student ? {
        student: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
